config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'memes#index'
  get "/popular", to: "memes#popular"
  resources :memes, only: [:show, :new, :create] do
    resources :comments, only: :create
    resources :votes, only: :create
  end

  resources :categories, only: [:index]

  resources :memes, only: [:show] do
    resources :comments, only:  [:create]
  end

  resources :users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :memes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meme, counter_cache: true
end

app/models/meme.rb
class Meme < ApplicationRecord
  self.inheritance_column = :_ # Disable STI
  # Associations
  belongs_to :category
  belongs_to :owner, class_name: "User", counter_cache: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :commentators, through: :comments, source: :user
  has_many :votes
  has_many :voters, through: :votes, source: :user

  # Enums
  enum type: { image: "image", gif: "gif" }

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :type, presence: true
  validates :url_source, presence: true, format: { with: %r{\Ahttps?://.+(png|gif|jpg)\z}, message: "Add a valid meme URL" }

  def has_voted?(user)
    votes.exists?(user: user)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Associations
  has_and_belongs_to_many :memes

  # Validations
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :memes, foreign_key: :owner_id
  has_many :votes
  has_many :voted_memes, through: :votes, source: :meme
  has_many :comments
  has_many :commented_memes, through: :comments, source: :meme

  # Validations
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  # Associations
  belongs_to :meme, counter_cache: true
  belongs_to :user

  # validations
  validates_uniqueness_of :user_id, scope: :meme_id, message: "Can't vote a meme more than once"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
    devise_parameter_sanitizer.permit(:account_update, keys:[:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    meme = Meme.find(params[:meme_id])
    comment = meme.comments.create(comment_params)
    unless comment.save
      flash[:alert] = "There was a problem creating the meme"
    end

    redirect_to meme_path(meme)
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  def index
    memes = Meme.all.order(created_at: :desc)
    @memes_by_date = memes.all.group_by { |meme| meme.created_at.to_date }
  end

  def show
    @meme = Meme.find(params[:id])
    @comment = Comment.new
  end

  def create
    @meme = current_user.memes.new(meme_params)
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render "new"
    end
  end

  def new
    @meme = Meme.new
  end

  def popular
    @memes = Meme.all.order(votes_count: :desc)
  end

  private
  def meme_params
    params.require(:meme).permit(:title, :url_source, :type, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    meme = Meme.find(params[:meme_id])
    meme.votes.create!(user: current_user)
    redirect_to meme_path(meme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/categories/index.html.erb
<% @categories.each do | category | %>

  <h2><%= category.name %></h2>
  <div class="categories-container">
    <%= render partial: "memes/meme", collection: category.memes %>
  </div>
<%end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/memes/_meme.html.erb
<%= link_to meme_path(meme) do %>
  <figure>
    <%= image_tag meme.url_source, alt: meme.title, width: "200px" %>
    <figcaption>Created by: <%= meme.owner.username %></figcaption>
  </figure>
<% end %>

app/views/memes/create.html.erb
<h1>Memes#create</h1>
<p>Find me in app/views/memes/create.html.erb</p>

app/views/memes/index.html.erb
<% @memes_by_date.each do |date, memes| %>

  <h2><%= date.strftime("%A, %b %-d") %></h2>
  <div class="memes-container">
    <%= render partial: "meme", collection: memes %>
  </div>
<% end %>

app/views/memes/new.html.erb
<h1>Create a meme!</h1>

<%= form_with model: @meme do | f | %>
  <ul>
    <% @meme.errors.full_messages.each do | message | %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>


  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url_source %>
    <%= f.text_field :url_source %>
  </p>

  <p>
    <%= f.label :type %>
    <%= f.select :type, Meme.types %>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>

  <%= f.submit "Create!"%>

<% end %>

app/views/memes/popular.html.erb
<h1>Most popular memes</h1>
  <div class="memes-container">
    <%= render partial: "memes/meme", collection: @memes %>
  </div>

app/views/memes/show.html.erb
<h1><%= @meme.title %>!</h1>

<%= image_tag @meme.url_source, alt: @meme.title, width: "400px" %>

  <p>
    Category: <%= @meme.category.name %>
  </p>

<div>
  Votes: <%= @meme.votes_count %>
  <% if user_signed_in? %>
    <% unless @meme.has_voted?(current_user) %>
      <%= button_to "Vote!", meme_votes_path(@meme), method: :post %>
    <% end %>
  <% else %>
    Login to vote!
  <% end %>
</div>

<div>
  <h2>Comments</h2>

  <% unless user_signed_in?%>
    <p>Login to add a comment</p>
  <% end %>

  <%= form_for [@meme, @comment] do | f | %>
    <%= f.text_area :body %>
    <%= f.submit "Comment" %>
  <% end %>

  <ul>
    <% @meme.comments.each do | comment |%>
      <li><%=comment.user.username %>: <%= comment.body %></li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<h1>My account</h1>

<p>Username: <%= current_user.username %></p>
<p>Email: <%= current_user.email %></p>
<p># of memes: <%= current_user.memes_count %></p>

<%= link_to "Edit", edit_user_registration_path %>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>