config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'memes#index'
  get "/popular", to: "memes#popular"
  resources :memes, only: [:show, :new, :create] do
    resources :comments, only: :create
    resources :votes, only: :create
  end

  resources :categories, only: [:index]

  resources :memes, only: [:show] do
    resources :comments, only:  [:create]
  end

  resources :users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :memes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meme, counter_cache: true
end

app/models/meme.rb
class Meme < ApplicationRecord
  self.inheritance_column = :_ # Disable STI
  # Associations
  belongs_to :category
  belongs_to :owner, class_name: "User", counter_cache: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :commentators, through: :comments, source: :user
  has_many :votes
  has_many :voters, through: :votes, source: :user

  # Enums
  enum type: { image: "image", gif: "gif" }

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :type, presence: true
  validates :url_source, presence: true, format: { with: %r{\Ahttps?://.+(png|gif|jpg)\z}, message: "Add a valid meme URL" }

  def has_voted?(user)
    votes.exists?(user: user)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Associations
  has_and_belongs_to_many :memes

  # Validations
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :memes, foreign_key: :owner_id
  has_many :votes
  has_many :voted_memes, through: :votes, source: :meme
  has_many :comments
  has_many :commented_memes, through: :comments, source: :meme

  # Validations
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  # Associations
  belongs_to :meme, counter_cache: true
  belongs_to :user

  # validations
  validates_uniqueness_of :user_id, scope: :meme_id, message: "Can't vote a meme more than once"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    meme = Meme.find(params[:meme_id])
    comment = meme.comments.create(comment_params)
    unless comment.save
      flash[:alert] = "There was a problem creating the meme"
    end

    redirect_to meme_path(meme)
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  def index
    memes = Meme.all.order(created_at: :desc)
    @memes_by_date = memes.all.group_by { |meme| meme.created_at.to_date }
  end

  def show
    @meme = Meme.find(params[:id])
    @comment = Comment.new
  end

  def create
    @meme = current_user.memes.new(meme_params)
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render "new"
    end
  end

  def new
    @meme = Meme.new
  end

  def popular
    @memes = Meme.all.order(votes_count: :desc)
  end

  private
  def meme_params
    params.require(:meme).permit(:title, :url_source, :type, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    meme = Meme.find(params[:meme_id])
    meme.votes.create!(user: current_user)
    redirect_to meme_path(meme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memehub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="main-content">
      <header class="header">
        <%= link_to root_path do %>
          <%= image_tag "memehub.png", width: "150px"%>
        <% end %>

        <nav class="nav">
          <%= link_to "By Category", categories_path %>
          <%= link_to "By Popular", popular_path %>
          <%= link_to "Search", "" %>

          <% if user_signed_in? %>
            <%= link_to "Create meme", new_meme_path %>
            <p>Welcome, <%= current_user.username %></p>
            <%= link_to "My account", users_path%>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log in", user_session_path %>
          <% end %>
        </nav>
      </header>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

      <footer class="signature">
        Made by Erick Saavedra
      </footer>
    </div>

  </body>
</html>